name: currency_converter
description: "A beautiful, responsive, and delightfully animated mobile app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Animation
  cupertino_icons: ^1.0.8
  lottie: ^3.1.3

  # State Management & Architecture
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  formz: ^0.6.1

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  intl: ^0.20.2
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true