// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVLYTZQ_h-UrFLVc-d3RXCZ1PWxlf7jEA',
    appId: '1:139221834897:web:a0f7f3549dda7fc61e7330',
    messagingSenderId: '139221834897',
    projectId: 'currency-converter-app-flutter',
    authDomain: 'currency-converter-app-flutter.firebaseapp.com',
    storageBucket: 'currency-converter-app-flutter.firebasestorage.app',
    measurementId: 'G-WXLWEV599P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzrzzPUNNo50-qC9SqwxxyzeifxDIa5C8',
    appId: '1:139221834897:android:06bd09fb25f33d6e1e7330',
    messagingSenderId: '139221834897',
    projectId: 'currency-converter-app-flutter',
    storageBucket: 'currency-converter-app-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB8dcj9hhfjeGMOJQPEUDqBMF2PEzosoE',
    appId: '1:139221834897:ios:133e0006a48aea6d1e7330',
    messagingSenderId: '139221834897',
    projectId: 'currency-converter-app-flutter',
    storageBucket: 'currency-converter-app-flutter.firebasestorage.app',
    iosBundleId: 'com.example.currencyconverter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB8dcj9hhfjeGMOJQPEUDqBMF2PEzosoE',
    appId: '1:139221834897:ios:133e0006a48aea6d1e7330',
    messagingSenderId: '139221834897',
    projectId: 'currency-converter-app-flutter',
    storageBucket: 'currency-converter-app-flutter.firebasestorage.app',
    iosBundleId: 'com.example.currencyconverter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVLYTZQ_h-UrFLVc-d3RXCZ1PWxlf7jEA',
    appId: '1:139221834897:web:33f675b0eeec97301e7330',
    messagingSenderId: '139221834897',
    projectId: 'currency-converter-app-flutter',
    authDomain: 'currency-converter-app-flutter.firebaseapp.com',
    storageBucket: 'currency-converter-app-flutter.firebasestorage.app',
    measurementId: 'G-SS69ESGHE0',
  );
}
